### ISSUE TITLE
Like button changes to "Confirm" on click

### ISSUE THREAD

**Issue by kparzinger** [myApi/myApi#22]
Hi,
on my website the button does not work proberly.

If click on the button, the popup comes up for a millisecond and then there is not a 1 for 1 like there is a new button called "CONFIRM".

Only after performing a click on "COFIRM" the like goes to facebook.

New installation of myapi 1.3.1.

page: 213.239.198.140/gruenweg/

Thanks for have look at this

**Comment by thomaswelton** [comment]
This may be due to Facebook's protection againt "like jacking"
http://forum.developers.facebook.net/viewtopic.php?id=93201

**Comment by thomaswelton** [comment]
I'm going to close this issue as I do not think it's a myApi defect. But please if this problem does not resolve it's self soon please reopen it and I'll help you look into it, maybe the server you site is hosted on is known for spamming ect. That is just pure speculation however, this may be due to many things.
