### ISSUE TITLE
JFolder::create: Could not create directory

### ISSUE THREAD

**Issue by onorius** [myApi/myApi#27]
Hello
I installed in this morning myapi package. i'v made the apps setup in facebook, but when i tried to login i'v received this message:
 "JFolder::create: Could not create directory
Username or password do not match or you don't have an account"
My site url is http://masajladomiciliu.org/
can you have a look, please
Thank You
Kind Regards

**Comment by thomaswelton** [comment]
I clicked connect with Facebook and it create me an account. Can you try to replicate again? If you can replicate let me know which browser you are using.

Edit: To retest you link process you will first need to delete the linked user or unlink them from the myApi backend

**Comment by thomaswelton** [comment]
Also if you have a look at a Javascript error console you'll see some JS error, these are caused by the plugin setup of cssjscompress. The plugin is moving the compressed mootools file below the script tag that contains mootools code. Change the settings of that plugin to put compressed code before the first script tag instead of after the last in the bottom of the head.

**Comment by onorius** [comment]
Hello
I think everythink it's fine now... Can you have a look?
thank you so much
God bless you  :D

**Comment by thomaswelton** [comment]
I can no longer see that JS error so the changes in config looked like they worked. 
I also successfully logged in using Facebook. But I just want to confirm that you unlinked my account from the backend? Because I had to relink accounts using FB.

Thank you for supporting the myApi project. Please support the myApi project by writing a review here http://extensions.joomla.org/extensions/social-web/facebook-display/11624

**Comment by onorius** [comment]
Yes... i unlinked your account from the backend...
thank you again... and now i gonna go to post my review
