### ISSUE TITLE
Language file doesnt work for plugins and modules

### ISSUE THREAD

**Issue by IMspintheweb** [myApi/myApi#38]
works fine for component labels but the comment plugin has unmapped entries such as

PARAM_WIDTH_LABEL  
PARAM_NUMPOSTS_LABEL  
PARAM_SCHEME_LABEL  
PARAM_ACCESS_LABEL  
PARAM_ARTICLE_LABEL     PARAM_VIEW_BOX PARAM_VIEW_LINK PARAM_VIEW_NONE
PARAM_LIST_LABEL    PARAM_VIEW_BOX PARAM_VIEW_LINK PARAM_VIEW_NONE
PARAM_BLOG_LABEL    PARAM_VIEW_BOX PARAM_VIEW_LINK PARAM_VIEW_NONE
PARAM_SHOW_LABEL

**Comment by thomaswelton** [comment]
Yeah apologies for that, that defect is in version 1.3.3 but has already been confirmed fixed in the latest code in the master https://github.com/thomaswelton/myApi/zipball/master
If you want to install the master branch you can but it's not 100% tested, but I know that this defect is fixed.

I'll be packaging this together for version 1.3.4. This version also come with Real time subscriptions, and Facebook tab applications

**Comment by thomaswelton** [comment]
Also for now if you view the plugins from with the myApi component the language files work for the plugins (kind of) so for now it may help you get set up by reading those.

**Comment by IMspintheweb** [comment]
It's all good Thomas!  I'll wait for the 1.3.4 version to upgrade it

**Comment by IMspintheweb** [comment]
I was going to add a response on my review on the JED as that was a super fast reply but you can only add one review at a time...  feel free to quote this in your reply. Will be using your api for all my facebook connected sites!

**Comment by IMspintheweb** [comment]
upgraded anyway - nice fix!

**Comment by thomaswelton** [comment]
I need to apply the same fix for modules, they too have no language files. So for now I will reopen this defect.
