### ISSUE TITLE
Two Fatal errors

### ISSUE THREAD

**Issue by etkritikonspoudon** [myApi/myApi#48]
I got two Fatal Errors in the back end with the most recent version of myapi
- Fatal error: Call to undefined method JException::getAppId() in /home/mysite/public_html/administrator/components/com_myapi/views/plugin/view.html.php on line 77
- Fatal error: Call to undefined method JException::api() in /home/mysite/public_html/administrator/components/com_myapi/models/realtime.php on line 67

The second after saving the facebook ID, secret app codes, the first when clicking an menu item in myapi component

**Comment by thomaswelton** [comment]
Apologies for these issues your having with the master branch.
The master branch contains my latest work, I added some new features in last night then fell asleep :) So these are the problems I didn't test last night. If you have anymore please keep posting them, however you can reopen closed defects instead of making new ones if it's the same problem.

**Comment by etkritikonspoudon** [comment]
No apologies needed...you are putting so much effort into this, I see the code updated several times during the day...
...the only relevant issue for users is, how do we keep up...is there a new stable version planned soon to be the new standard (i.e. mainly those that happen to come across an issue will need to update) ?
